/// Static navigation route targets — every page in the
/// demo registers here so the sidebar can iterate.
pub(crate) const NAV_ITEMS: &[(&str, &str, &str)] = &[
    ("ℹ️", "About", "/"),
    ("🎬", "Animation", "/animation"),
    ("⏳", "Async", "/async"),
    ("⚙️", "Attrs", "/custom-attrs"),
    ("🏷️", "Badge", "/badge"),
    ("🔗", "Binding", "/component-binding"),
    ("🌐", "Browser", "/browser"),
    ("📷", "Camera", "/camera"),
    ("🎨", "Canvas", "/canvas"),
    ("🔀", "Condition", "/conditional"),
    ("🔢", "Counter", "/counter"),
    ("🏷️", "DynTag", "/dynamic-component"),
    ("🎯", "Event", "/event"),
    ("📄", "Form", "/form"),
    ("⏲️", "Timing", "/hooks-timing"),
    ("🌐", "Async", "/hooks-async"),
    ("🛡️", "Protect", "/hooks-protect"),
    ("🌍", "i18n", "/hooks-i18n"),
    ("🎮", "Game2D", "/game-2d"),
    ("🎲", "Game3D", "/game-3d"),
    ("💚", "KeepAlive", "/keep-alive"),
    ("♻️", "Lifecycle", "/lifecycle"),
    ("📝", "List", "/list"),
    ("💬", "Modal", "/modal"),
    ("👁️", "Observer", "/observer"),
    ("📡", "SSE", "/sse"),
    ("📋", "Select", "/select"),
    ("⏱️", "Timer", "/timer"),
    ("📁", "Upload", "/file-upload"),
    ("📊", "VList", "/virtual-list"),
    ("🔌", "WebSocket", "/websocket"),
];
